## Anatomical regions for each region in Shen Atlas

In [1]:
import json
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.patches as mpatches
import re
from itertools import combinations
%run functions-py.py

### shen_dictionary from professor Ralf Schmälzle has (almost) the same info as full_aal
For each region (identified by a number) the dictionary has the names and percentages of the all_regions it contains

In [20]:
the_dict=np.load('../Data/shen_dictionary.npy',allow_pickle=True).item()

In [21]:
with open("../Data/Parcellation/bioimage.json", "r") as read_file:
    my_dict= json.load(read_file)

In [22]:
with open("../Data/Parcellation/labeling_with_full_aal.json", "r") as read_file:
    my_names=json.load(read_file)

In [23]:
i=11
#the_dict[i]['name'].split(';')[0].split(' ')
#the_dict[i]['name']
the_dict[i]['coords']

[37.628787878787875, 35.4419191919192, 31.101010101010104]

In [25]:
my_dict['rois'][10]

{'x': 37.62, 'y': 35.39, 'z': 31.09, 'attr': [1, 3, 9, 9, 8]}

In [26]:
i=6
print(my_dict['rois'][i-1])
print(my_names[str(i)])
print(the_dict[i])

{'x': 14.56, 'y': 64.73, 'z': 3.64, 'attr': [1, 2, 5, 10, 3]}
{'Superior frontal gyrus, Dorsolateral R': '32%', 'Superior frontal gyrus, orbital Part R': '17%', 'Superior frontal gyrus, medial R': '31%', 'Superior frontal gyrus, medial Orbital R': '20%'}
{'coords': [14.581460674157299, 64.75280898876406, 3.682584269662925], 'name': '100.00% Frontal_Pole'}


### My ROIS (extended)

In [27]:
file="../Data/my_rois_net1_ordered.json"

In [11]:
networks=['Dorsal-Attention','Ventral-Attention','Salience','Frontal-Parietal','Default','Subcortical']
my_dict=regions_from_json(file,networks,verbose=False)
regions=my_dict['array']
lengths=my_dict['length']
r=np.sum(lengths)
print(r)

101


In [12]:
lims=create_limits(lengths)
print(lims)

[0, 4, 8, 18, 38, 82, 101]


In [188]:
#Names of regions of chosen networks. Based on labeling_with_full_aal.json
# ROIS={}
# for i in range(len(networks)):
#     net=networks[i]
#     regs=regions[lims[i]:lims[i+1]]
#     ROIS[net]={}
#     for reg in regs:
#         info= my_names[str(reg+1)]
#         for name in info.keys(): #name is the aal label
#             if name in list(ROIS[net].keys()):
#                 ROIS[net][name][0]= ROIS[net][name][0] + round(float(info[name].split('%')[0])/100,2) #sum up percentage
#                 ROIS[net][name][1]= ROIS[net][name][1] + 1 #incidence
#             else:
#                 ROIS[net][name]=[0,0] #starting it
#                 ROIS[net][name][0]=round(float(info[name].split('%')[0])/100,2) #recover percentage
#                 ROIS[net][name][1]=1  #starting incidence
#     for name in ROIS[net].keys():
#          ROIS[net][name][0]=round(ROIS[net][name][0],2) #round final percentage

In [189]:
#We save to cvs the regions for each network
for net in ROIS.keys():
    df = pd.DataFrame(list(ROIS[net].items()),columns = ['Regions','Percentage'])
    df.to_csv('../Data/ROIS/my_'+net+'.csv')

In [ ]:
# ROIS={}
# for i in range(len(combs)):
#     comb=combs[i]
#     regs=regions[lims[i]:lims[i+1]]
#     ROIS[comb]={}
#     for reg in regs:
#         info= the_dict[reg+1]['name']
#         parts= info.split(';')
#         for j in range(len(parts)):
#             if j == 0:
#                 perc = parts[j].split(' ')[0].split('%')[0]
#                 name = parts[j].split(' ')[1]
#             else:
#                 perc = parts[j].split(' ')[1].split('%')[0] #there's a space before
#                 name = parts[j].split(' ')[2]
#             perc= round(float(perc)/100,2)
#             if name in list(ROIS[comb].keys()):
#                 ROIS[comb][name][0]= ROIS[comb][name][0] + perc #sum up percentage
#                 ROIS[comb][name][1]= ROIS[comb][name][1] + 1 #incidence
#             else:
#                 ROIS[comb][name]=[0,0]
#                 ROIS[comb][name][0]= perc  # percentage
#                 ROIS[comb][name][1]=1     #starting incidence
#     for name in ROIS[comb].keys():
#          ROIS[comb][name][0]=round(ROIS[comb][name][0],2)  #round final percentage

In [ ]:
#We save to cvs the regions for each network
for net in ROIS.keys():
    df = pd.DataFrame(list(ROIS[net].items()),columns = ['Regions','Percentage'])
    df.to_csv('../Data/ROIS/the_'+net+'.csv')

In [21]:
#50,  51,  52,  62,  63, 184, 185, 186, 187, 189, 190, 196, 197
print(my_names[str(51)])
print(my_names[str(52)])
print(my_names[str(53)])
print(my_names[str(63)])
print(my_names[str(64)])
print(my_names[str(185)])
print(my_names[str(186)])
print(my_names[str(187)])
print(my_names[str(188)])
print(my_names[str(189)])
print(my_names[str(190)])
print(my_names[str(197)])
print(my_names[str(198)])

{'Fusiform gyrus R': '19%', 'Temporal pole: middle temporal Gyrus R': '53%'}
{'Temporal pole: middle temporal Gyrus R': '69%', 'Temporal pole: superior temporal gyrus R': '25%'}
{'Temporal pole: superior temporal gyrus R': '38%', 'Middle temporal gyrus R': '24%', 'Temporal pole: middle temporal Gyrus R': '34%'}
{'Superior temporal gyrus R': '46%', 'Middle temporal gyrus R': '54%'}
{'Superior temporal gyrus R': '21%', 'Middle temporal gyrus R': '72%'}
{'Temporal pole: middle temporal Gyrus L': '21%', 'Inferior temporal gyrus L': '60%'}
{'Temporal pole: superior temporal gyrus L': '47%', 'Temporal pole: middle temporal Gyrus L': '47%'}
{'Middle temporal gyrus L': '26%', 'Temporal pole: middle temporal Gyrus L': '52%', 'Inferior temporal gyrus L': '15%'}
{'Superior temporal gyrus L': '25%', 'Temporal pole: superior temporal gyrus L': '49%', 'Middle temporal gyrus L': '17%'}
{'Temporal pole: superior temporal gyrus L': '11%', 'Temporal pole: middle temporal Gyrus L': '44%', 'Fusiform gyrus

## My_ROIS (official)

In [3]:
lengths2=np.array(
          [[7, 0,1,1,0,1],
          [12,4,0,2,2,0],
          [15,0,0,2,13,14]])
print(np.sum(lengths2,axis=0))
print(np.sum(lengths2,axis=1))

[34  4  1  5 15 15]
[10 20 44]


In [4]:
networks=['Salience','Frontal-Parietal','Default']
lobes=['Prefrontal' , 'MotorStrip', 'Insula' , 'Parietal','Temporal','Limbic']

In [5]:
#Distribution of regions by network and lobe
pd.DataFrame(lengths2, columns = lobes, index=networks)

Prefrontal  MotorStrip  Insula  Parietal  Temporal  Limbic
Salience                   7           0       1         1         0       1
Frontal-Parietal          12           4       0         2         2       0
Default                   15           0       0         2        13      14

In [15]:
my_dict=regions_from_json(file,networks,verbose=False)
regions=my_dict['array']
lengths=my_dict['length']
r=np.sum(lengths)
print(r)

74


In [16]:
regions

array([  8,  10,  14,  19, 143, 149, 154,  35,  46,  90,   6,   7,  13,
        18,  20,  21, 141, 142, 146, 153, 155, 156,  29,  30, 163, 164,
        42, 183,  68,  69,   0,   4,   5,   9,  11,  12, 137, 138, 139,
       140, 144, 145, 147, 148, 150,  41, 182,  50,  51,  52,  62,  63,
       184, 185, 186, 187, 189, 190, 196, 197,  82,  84,  85,  89,  92,
        94, 218, 221, 224, 225, 226, 228, 229, 232])

In [9]:
combs=[a+"-"+b for a in networks for b in lobes]

In [10]:
lims=create_limits(lengths2.flatten())
lims

[0, 7, 7, 8, 9, 9, 10, 22, 26, 26, 28, 30, 30, 45, 45, 45, 47, 60, 74]

In [11]:
#Separation of regions by network-lobe
for i in range(len(combs)):
    comb=combs[i]
    print(comb)
    regs=regions[lims[i]:lims[i+1]]
    print(regs)

Salience-Prefrontal
[  8  10  14  19 143 149 154]
Salience-MotorStrip
[]
Salience-Insula
[35]
Salience-Parietal
[46]
Salience-Temporal
[]
Salience-Limbic
[90]
Frontal-Parietal-Prefrontal
[  6   7  13  18  20  21 141 142 146 153 155 156]
Frontal-Parietal-MotorStrip
[ 29  30 163 164]
Frontal-Parietal-Insula
[]
Frontal-Parietal-Parietal
[ 42 183]
Frontal-Parietal-Temporal
[68 69]
Frontal-Parietal-Limbic
[]
Default-Prefrontal
[  0   4   5   9  11  12 137 138 139 140 144 145 147 148 150]
Default-MotorStrip
[]
Default-Insula
[]
Default-Parietal
[ 41 182]
Default-Temporal
[ 50  51  52  62  63 184 185 186 187 189 190 196 197]
Default-Limbic
[ 82  84  85  89  92  94 218 221 224 225 226 228 229 232]


In [36]:
#Names of regions of chosen networks. Based on labeling_with_full_aal.json
ROIS={}
for i in range(len(networks)):
    net=networks[i]
    regs=regions[lims[i]:lims[i+1]]
    ROIS[net]={}
    for reg in regs:
        info= my_names[str(reg+1)]
        for name in info.keys(): #name is the aal label
            if name in list(ROIS[net].keys()):
                ROIS[net][name][0]= ROIS[net][name][0] + round(float(info[name].split('%')[0])/100,2) #sum up percentage
                ROIS[net][name][1]= ROIS[net][name][1] + 1 #incidence
            else:
                ROIS[net][name]=[0,0] #starting it
                ROIS[net][name][0]=round(float(info[name].split('%')[0])/100,2) #recover percentage
                ROIS[net][name][1]=1  #starting incidence
    for name in ROIS[net].keys():
         ROIS[net][name][0]=round(ROIS[net][name][0],2) #round final percentage

In [ ]:
#We save to cvs the regions for each network
for net in ROIS.keys():
    df = pd.DataFrame(list(ROIS[net].items()),columns = ['Regions','Percentage'])
    df.to_csv('../Data/ROIS/my_'+net+'.csv')

In [36]:
ROIS={}
for i in range(len(combs)):
    comb=combs[i]
    regs=regions[lims[i]:lims[i+1]]
    ROIS[comb]={}
    for reg in regs:
        info= the_dict[reg+1]['name']
        parts= info.split(';')
        for j in range(len(parts)):
            if j == 0:
                perc = parts[j].split(' ')[0].split('%')[0]
                name = parts[j].split(' ')[1]
            else:
                perc = parts[j].split(' ')[1].split('%')[0] #there's a space before
                name = parts[j].split(' ')[2]
            perc= round(float(perc)/100,2)
            if name in list(ROIS[comb].keys()):
                ROIS[comb][name][0]= ROIS[comb][name][0] + perc #sum up percentage
                ROIS[comb][name][1]= ROIS[comb][name][1] + 1 #incidence
            else:
                ROIS[comb][name]=[0,0]
                ROIS[comb][name][0]= perc  # percentage
                ROIS[comb][name][1]=1     #starting incidence
    for name in ROIS[comb].keys():
         ROIS[comb][name][0]=round(ROIS[comb][name][0],2)  #round final percentage

In [43]:
for net in ROIS.keys():
    if (len(ROIS[net])>1):
        df = pd.DataFrame(list(ROIS[net].items()),columns = ['Regions','Percentage'])
        df.to_csv('../Data/ROIS/the_'+net+'.csv')

## My_ROIS (MNI coordinates)

In [15]:
lengths2=np.array(
          [[7, 0,1,1,0,1],
          [12,4,0,2,2,0],
          [15,0,0,2,13,14]])
print(np.sum(lengths2,axis=0))
print(np.sum(lengths2,axis=1))

[34  4  1  5 15 15]
[10 20 44]


In [16]:
networks=['Salience','Frontal-Parietal','Default']
lobes=['Prefrontal' , 'MotorStrip', 'Insula' , 'Parietal','Temporal','Limbic']

In [17]:
pd.DataFrame(lengths2, columns = lobes, index=networks)

Prefrontal  MotorStrip  Insula  Parietal  Temporal  Limbic
Salience                   7           0       1         1         0       1
Frontal-Parietal          12           4       0         2         2       0
Default                   15           0       0         2        13      14

In [28]:
my_dict=regions_from_json(file,networks,verbose=False)
regions=my_dict['array']
lengths=my_dict['length']
r=np.sum(lengths)
print(r)

74


In [16]:
regions

array([  8,  10,  14,  19, 143, 149, 154,  35,  46,  90,   6,   7,  13,
        18,  20,  21, 141, 142, 146, 153, 155, 156,  29,  30, 163, 164,
        42, 183,  68,  69,   0,   4,   5,   9,  11,  12, 137, 138, 139,
       140, 144, 145, 147, 148, 150,  41, 182,  50,  51,  52,  62,  63,
       184, 185, 186, 187, 189, 190, 196, 197,  82,  84,  85,  89,  92,
        94, 218, 221, 224, 225, 226, 228, 229, 232])

In [29]:
combs=[a+"-"+b for a in networks for b in lobes]

In [30]:
lims=create_limits(lengths2.flatten())
lims

[0, 7, 7, 8, 9, 9, 10, 22, 26, 26, 28, 30, 30, 45, 45, 45, 47, 60, 74]

In [31]:
for i in range(len(combs)):
    comb=combs[i]
    print(comb)
    regs=regions[lims[i]:lims[i+1]]
    print(regs)

Salience-Prefrontal
[  8  10  14  19 143 149 154]
Salience-MotorStrip
[]
Salience-Insula
[35]
Salience-Parietal
[46]
Salience-Temporal
[]
Salience-Limbic
[90]
Frontal-Parietal-Prefrontal
[  6   7  13  18  20  21 141 142 146 153 155 156]
Frontal-Parietal-MotorStrip
[ 29  30 163 164]
Frontal-Parietal-Insula
[]
Frontal-Parietal-Parietal
[ 42 183]
Frontal-Parietal-Temporal
[68 69]
Frontal-Parietal-Limbic
[]
Default-Prefrontal
[  0   4   5   9  11  12 137 138 139 140 144 145 147 148 150]
Default-MotorStrip
[]
Default-Insula
[]
Default-Parietal
[ 41 182]
Default-Temporal
[ 50  51  52  62  63 184 185 186 187 189 190 196 197]
Default-Limbic
[ 82  84  85  89  92  94 218 221 224 225 226 228 229 232]


In [61]:
MNI=[]

In [62]:
for reg in regions:
    vec=['a']*4
    vec[0]=int(reg+1)
    vec[1:]=np.round(the_dict[reg+1]['coords'],2)
    MNI.append(vec)

In [64]:
MNI_tab=pd.DataFrame(MNI, columns = ["Region","x","y","z"])

In [65]:
MNI_tab.to_csv('../Data/ROIS/the_coordinates.csv')